services:
  
  mlflow:
    build: 
      context: .
      dockerfile: Dockerfile.mlflow
    working_dir: /app
    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./mlruns:/app/mlruns
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /app/mlruns
      --allowed-hosts '*'

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_NAME=lightgbm_model
      - MODEL_ALIAS=champion
    depends_on:
      - mlflow
