services:

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    working_dir: /app
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    ports:
      - "5000:5000"
    env_file:
      - .env  
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root mlflow-artifacts:/
      --artifacts-destination s3://flight-predictor-artifacts-2026-1/
      --serve-artifacts
      --allowed-hosts "*"
      --cors-allowed-origins "*"
  api:
    build:
      context: 853506921311.dkr.ecr.eu-north-1.amazonaws.com/flight-price-predictor
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8089:8089"
    volumes:
      - ./mlruns:/app/mlruns
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_NAME=lightgbm_model
      - MODEL_ALIAS=champion
      - LOAD_FROM=mlflow
      - CHAMPION_MODEL_PATH=models/lightgbm_model.joblib
      - LOG_LEVEL=INFO
    depends_on:
      - mlflow
